version: "3.2"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_USER=challenge
      - POSTGRES_DB=challenge
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  challenge:
    image: com.challenge/reports
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - RESOURCE_PATH=/reports
    volumes:
      - ./reports:/reports